Document: classicwm
Title: Debian classicwm Manual
Author: <insert document author here>
Abstract: This manual describes what classicwm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/classicwm/classicwm.sgml.gz

Format: postscript
Files: /usr/share/doc/classicwm/classicwm.ps.gz

Format: text
Files: /usr/share/doc/classicwm/classicwm.text.gz

Format: HTML
Index: /usr/share/doc/classicwm/html/index.html
Files: /usr/share/doc/classicwm/html/*.html
